  Updates an existing task information
    ---
    tags:
      - Tasks
    parameters:
      - name: task_id
        in: path
        type: string
        required: true
        description: The id of the task
      - name: update_request
        in: body
        required: true

    responses:
      404:
        description: user not found!
      400:
        description: Not a JSON
      200:
        description: request executed successfully